import type { UiLocale } from "./types";

type Messages = Record<string, string>;
type AdditionalLocale = Exclude<UiLocale, "zh-CN" | "zh-TW" | "en" | "ja">;

export function createAdditionalLocaleMessages(english: Messages): Record<AdditionalLocale, Messages> {
  const locale = (values: Messages) => ({ ...english, ...values });
  return {
    ko: locale({
      localeName: "한국어",
      extensionDescription: "자체 OpenAI 호환 API로 선택한 텍스트나 웹페이지를 번역합니다.", actionTitle: "번역기 설정 열기", contextTranslatePage: "이 페이지 번역", contextTranslateSelection: "선택한 텍스트 번역",
      contentTranslating: "번역 중…", contentClose: "닫기", contentRestore: "원문 복원", contentOpenSettings: "설정 열기", contentRunning: "번역 진행 중", contentFailed: "실패", contentCancelled: "취소됨", contentRetry: "실패 항목 재시도", contentSegmentsSent: "개의 텍스트 구간을 전송합니다", contentRequestLimit: "최대 {count}개 요청", contentStarting: "번역을 시작하는 중…", contentNewContent: "새 콘텐츠를 발견했습니다. 추가 번역 중…", contentCompletion: "번역 완료! 총 {count}개 텍스트 구간을 번역했습니다(새 콘텐츠 감시 계속)", contentPartialCompletion: "번역 완료! 총 {count}개 번역, {failed}개 실패(새 콘텐츠 감시 계속)",
      brandTagline: "모든 웹페이지를 위한 집중형 AI 번역 도구", uiLanguage: "인터페이스 언어", followBrowser: "브라우저 설정 따르기", autoDetect: "자동 감지",
      settingsTab: "설정", aboutTab: "소개", pageNavigation: "설정 페이지 탐색", save: "프로필 저장", add: "프로필 추가", remove: "삭제", test: "연결 테스트", active: "사용 중", profiles: "프로필",
      profilesEyebrow: "저장됨", editingEyebrow: "업데이트", createEyebrow: "구성", newProfile: "새 프로필", editProfile: "프로필 편집", noProfiles: "아직 프로필이 없습니다.", name: "이름", apiKey: "API 키", model: "모델", language: "언어",
      source: "원본 언어", target: "대상 언어", mode: "번역 모드", replace: "원문 대체", preserve: "이중 언어 대조", connected: "연결되었습니다. 이 프로필이 활성화되었습니다.", connectionFailed: "연결에 실패했습니다.", invalidUrl: "Base URL은 유효한 절대 URL이어야 합니다.", insecureUrl: "Base URL은 HTTPS를 사용해야 합니다(localhost만 HTTP 허용).", credentialsUrl: "Base URL에 인증 정보를 포함할 수 없습니다.", queryUrl: "Base URL에 쿼리나 프래그먼트를 포함할 수 없습니다.", privacy: "명시적으로 번역할 때만 페이지 텍스트를 읽고 설정한 API로만 전송합니다. 저장하거나 사용 통계를 수집하지 않습니다.", unsupported: "브라우저 확장 프로그램이 이 페이지를 번역할 수 없습니다.", ok: "확인", confirm: "삭제", cancel: "취소", saved: "프로필을 저장했습니다.", confirmDelete: "이 프로필을 삭제하시겠습니까? 되돌릴 수 없습니다.", deleted: "프로필을 삭제했습니다.",
      aboutEyebrow: "읽기를 위한 설계", aboutTitle: "방해 없는 몰입형 번역", aboutIntro: "선택한 AI 모델로 작동하는 가벼운 브라우저 확장 프로그램입니다. 페이지를 떠나지 않고 선택한 텍스트나 전체 페이지를 번역하세요.", featureFree: "무료", featureFreeDesc: "확장 프로그램 구독료 없이 설정한 API로 사용할 수 있습니다.", featureAllInOne: "올인원 AI 번역", featureAllInOneDesc: "모델, 언어, 선택 영역 및 전체 페이지 번역을 한곳에서 관리합니다.", featureSelection: "선택 텍스트 번역", featureSelectionDesc: "페이지를 떠나지 않고 선택한 문장의 번역을 확인합니다.", featureBilingual: "이중 언어 대조", featureBilingualDesc: "원문과 번역을 함께 보며 읽고 학습할 수 있습니다.", featureLanguages: "다국어 지원", featureLanguagesDesc: "다양한 주요 언어 사이를 번역합니다.", featureNoAds: "광고 없음", featureNoAdsDesc: "광고나 홍보 팝업 없이 읽기에 집중합니다.", featurePure: "순수함", featurePureDesc: "로컬 프로필과 무수집 원칙으로 번역에만 집중합니다.", featureAccurate: "정확함", featureAccurateDesc: "대규모 언어 모델이 문맥을 이해해 정확하게 번역합니다.", featureFluent: "유창함", featureFluentDesc: "읽기 편한 표현으로 언어 간 의미를 자연스럽게 전달합니다.", featureNatural: "자연스러움", featureNaturalDesc: "딱딱한 직역보다 실제 언어에 가까운 표현을 제공합니다.", aboutClosingTitle: "오직 번역을 위해 설계", aboutClosing: "언어 장벽을 쉽게 넘어 웹의 모든 내용을 이해하세요."
    }),
    fr: locale({
      localeName: "Français",
      extensionDescription: "Traduisez du texte sélectionné ou des pages web avec votre API compatible OpenAI.", actionTitle: "Ouvrir les paramètres du traducteur", contextTranslatePage: "Traduire cette page", contextTranslateSelection: "Traduire le texte sélectionné",
      contentTranslating: "Traduction…", contentClose: "Fermer", contentRestore: "Restaurer l’original", contentOpenSettings: "Ouvrir les paramètres", contentRunning: "Traduction en cours", contentFailed: "échecs", contentCancelled: "annulée", contentRetry: "Réessayer les échecs", contentSegmentsSent: "segments de texte seront envoyés", contentRequestLimit: "jusqu’à {count} requêtes", contentStarting: "Démarrage de la traduction…", contentNewContent: "Nouveau contenu détecté. Traduction ajoutée…", contentCompletion: "Traduction terminée ! {count} segments traduits (surveillance du nouveau contenu maintenue)", contentPartialCompletion: "Traduction terminée ! {count} segments traduits, {failed} échecs (surveillance maintenue)",
      brandTagline: "Un outil de traduction IA dédié à chaque page web", uiLanguage: "Langue de l’interface", followBrowser: "Suivre le navigateur", autoDetect: "Détection automatique",
      settingsTab: "Configuration", aboutTab: "À propos", pageNavigation: "Navigation des paramètres", save: "Enregistrer le profil", add: "Ajouter un profil", remove: "Supprimer", test: "Tester la connexion", active: "Actif", profiles: "Profils", profilesEyebrow: "Enregistrés", editingEyebrow: "Mise à jour", createEyebrow: "Configuration", newProfile: "Nouveau profil", editProfile: "Modifier le profil", noProfiles: "Aucun profil pour le moment.", name: "Nom", apiKey: "Clé API", model: "Modèle", language: "Langues", source: "Langue source", target: "Langue cible", mode: "Mode de traduction", replace: "Remplacer l’original", preserve: "Comparaison bilingue",
      connected: "Connexion réussie. Ce profil est maintenant actif.", connectionFailed: "Échec de la connexion.", invalidUrl: "L’URL de base doit être une URL absolue valide.", insecureUrl: "L’URL de base doit utiliser HTTPS (HTTP uniquement pour localhost).", credentialsUrl: "L’URL de base ne doit pas contenir d’identifiants.", queryUrl: "L’URL de base ne doit pas contenir de requête ni de fragment.", privacy: "Le texte est lu uniquement après une traduction explicite et envoyé seulement à l’API configurée. Il n’est ni enregistré ni utilisé pour la télémétrie.", unsupported: "Cette page ne peut pas être traduite par une extension de navigateur.", ok: "OK", confirm: "Supprimer", cancel: "Annuler", saved: "Profil enregistré.", confirmDelete: "Supprimer ce profil ? Cette action est irréversible.", deleted: "Profil supprimé.",
      aboutEyebrow: "Conçu pour la lecture", aboutTitle: "Traduire sans distraction", aboutIntro: "Une extension légère propulsée par le modèle IA de votre choix. Traduisez une sélection ou une page entière sans quitter votre lecture.", featureFree: "Gratuit", featureFreeDesc: "Aucun abonnement à l’extension ; utilisez simplement votre API configurée.", featureAllInOne: "Traduction IA tout-en-un", featureAllInOneDesc: "Gérez modèles, langues, sélections et pages entières au même endroit.", featureSelection: "Traduction de sélection", featureSelectionDesc: "Traduisez un passage sans quitter la page.", featureBilingual: "Comparaison bilingue", featureBilingualDesc: "Conservez l’original à côté de la traduction pour lire et apprendre.", featureLanguages: "Plusieurs langues", featureLanguagesDesc: "Traduisez entre de nombreuses langues courantes.", featureNoAds: "Sans publicité", featureNoAdsDesc: "Aucune publicité ni fenêtre promotionnelle pour interrompre la lecture.", featurePure: "Épuré", featurePureDesc: "Profils locaux, aucune télémétrie et une expérience dédiée à la traduction.", featureAccurate: "Précis", featureAccurateDesc: "Les grands modèles comprennent le contexte pour mieux restituer le sens.", featureFluent: "Fluide", featureFluentDesc: "Des formulations lisibles font circuler naturellement les idées.", featureNatural: "Naturel", featureNaturalDesc: "Une expression authentique plutôt qu’une traduction mot à mot.", aboutClosingTitle: "Conçu uniquement pour traduire", aboutClosing: "Franchissez les barrières linguistiques et comprenez tout le contenu du Web."
    }),
    de: locale({
      localeName: "Deutsch",
      extensionDescription: "Übersetzen Sie ausgewählten Text oder Webseiten mit Ihrer OpenAI-kompatiblen API.", actionTitle: "Übersetzer-Einstellungen öffnen", contextTranslatePage: "Diese Seite übersetzen", contextTranslateSelection: "Ausgewählten Text übersetzen",
      contentTranslating: "Wird übersetzt…", contentClose: "Schließen", contentRestore: "Original wiederherstellen", contentOpenSettings: "Einstellungen öffnen", contentRunning: "Übersetzung läuft", contentFailed: "fehlgeschlagen", contentCancelled: "abgebrochen", contentRetry: "Fehler erneut versuchen", contentSegmentsSent: "Textabschnitte werden gesendet", contentRequestLimit: "bis zu {count} Anfragen", contentStarting: "Übersetzung wird gestartet…", contentNewContent: "Neue Inhalte gefunden. Übersetzung wird ergänzt…", contentCompletion: "Übersetzung abgeschlossen! {count} Textabschnitte übersetzt (neue Inhalte werden weiter überwacht)", contentPartialCompletion: "Übersetzung abgeschlossen! {count} übersetzt, {failed} fehlgeschlagen (Überwachung läuft weiter)",
      brandTagline: "Ein fokussiertes KI-Übersetzungswerkzeug für jede Webseite", uiLanguage: "Oberflächensprache", followBrowser: "Browsersprache verwenden", autoDetect: "Automatisch erkennen", settingsTab: "Einstellungen", aboutTab: "Info", pageNavigation: "Navigation der Einstellungen", save: "Profil speichern", add: "Profil hinzufügen", remove: "Löschen", test: "Verbindung testen", active: "Aktiv", profiles: "Profile", profilesEyebrow: "Gespeichert", editingEyebrow: "Aktualisieren", createEyebrow: "Konfigurieren", newProfile: "Neues Profil", editProfile: "Profil bearbeiten", noProfiles: "Noch keine Profile.", name: "Name", apiKey: "API-Schlüssel", model: "Modell", language: "Sprachen", source: "Ausgangssprache", target: "Zielsprache", mode: "Übersetzungsmodus", replace: "Original ersetzen", preserve: "Zweisprachiger Vergleich",
      connected: "Verbindung erfolgreich. Dieses Profil ist jetzt aktiv.", connectionFailed: "Verbindung fehlgeschlagen.", invalidUrl: "Die Base URL muss eine gültige absolute URL sein.", insecureUrl: "Die Base URL muss HTTPS verwenden (HTTP nur für localhost).", credentialsUrl: "Die Base URL darf keine Zugangsdaten enthalten.", queryUrl: "Die Base URL darf keine Abfrage oder Fragmentkennung enthalten.", privacy: "Seitentext wird nur nach ausdrücklicher Übersetzung gelesen und nur an die konfigurierte API gesendet. Er wird weder gespeichert noch für Telemetrie genutzt.", unsupported: "Diese Seite kann von Browser-Erweiterungen nicht übersetzt werden.", ok: "OK", confirm: "Löschen", cancel: "Abbrechen", saved: "Profil gespeichert.", confirmDelete: "Dieses Profil löschen? Dies kann nicht rückgängig gemacht werden.", deleted: "Profil gelöscht.",
      aboutEyebrow: "Zum Lesen entwickelt", aboutTitle: "Übersetzen ohne Ablenkung", aboutIntro: "Eine schlanke Browser-Erweiterung mit dem KI-Modell Ihrer Wahl. Übersetzen Sie markierten Text oder ganze Seiten, ohne den Lesefluss zu verlassen.", featureFree: "Kostenlos", featureFreeDesc: "Keine Abo-Gebühr für die Erweiterung; sie nutzt Ihre konfigurierte API.", featureAllInOne: "KI-Übersetzung aus einer Hand", featureAllInOneDesc: "Modelle, Sprachen, Auswahl- und Seitenübersetzung an einem Ort.", featureSelection: "Auswahl übersetzen", featureSelectionDesc: "Markierte Passagen direkt auf der Seite übersetzen.", featureBilingual: "Zweisprachiger Vergleich", featureBilingualDesc: "Original und Übersetzung gemeinsam lesen und vergleichen.", featureLanguages: "Viele Sprachen", featureLanguagesDesc: "Zwischen zahlreichen verbreiteten Sprachen übersetzen.", featureNoAds: "Werbefrei", featureNoAdsDesc: "Keine Werbung oder störenden Werbefenster.", featurePure: "Pur", featurePureDesc: "Lokale Profile, keine Telemetrie und voller Fokus auf Übersetzung.", featureAccurate: "Präzise", featureAccurateDesc: "Leistungsfähige Sprachmodelle berücksichtigen den Kontext.", featureFluent: "Flüssig", featureFluentDesc: "Gut lesbare Formulierungen übertragen Gedanken mühelos.", featureNatural: "Natürlich", featureNaturalDesc: "Authentische Sprache statt starrer Wort-für-Wort-Ausgabe.", aboutClosingTitle: "Nur fürs Übersetzen geschaffen", aboutClosing: "Überwinden Sie Sprachbarrieren und verstehen Sie alle Inhalte im Web."
    }),
    es: locale({
      localeName: "Español",
      extensionDescription: "Traduce texto seleccionado o páginas web con tu API compatible con OpenAI.", actionTitle: "Abrir la configuración del traductor", contextTranslatePage: "Traducir esta página", contextTranslateSelection: "Traducir el texto seleccionado",
      contentTranslating: "Traduciendo…", contentClose: "Cerrar", contentRestore: "Restaurar original", contentOpenSettings: "Abrir configuración", contentRunning: "Traducción en curso", contentFailed: "fallidos", contentCancelled: "cancelada", contentRetry: "Reintentar fallidos", contentSegmentsSent: "segmentos de texto se enviarán", contentRequestLimit: "hasta {count} solicitudes", contentStarting: "Iniciando traducción…", contentNewContent: "Se encontró contenido nuevo. Añadiendo traducción…", contentCompletion: "¡Traducción completada! {count} segmentos traducidos (se seguirá observando contenido nuevo)", contentPartialCompletion: "¡Traducción completada! {count} traducidos, {failed} fallidos (la observación continúa)",
      brandTagline: "Una herramienta de traducción con IA para cualquier página web", uiLanguage: "Idioma de la interfaz", followBrowser: "Seguir el navegador", autoDetect: "Detección automática", settingsTab: "Configuración", aboutTab: "Información", pageNavigation: "Navegación de configuración", save: "Guardar perfil", add: "Añadir perfil", remove: "Eliminar", test: "Probar conexión", active: "Activo", profiles: "Perfiles", profilesEyebrow: "Guardados", editingEyebrow: "Actualizar", createEyebrow: "Configurar", newProfile: "Nuevo perfil", editProfile: "Editar perfil", noProfiles: "Aún no hay perfiles.", name: "Nombre", apiKey: "Clave API", model: "Modelo", language: "Idiomas", source: "Idioma de origen", target: "Idioma de destino", mode: "Modo de traducción", replace: "Sustituir original", preserve: "Comparación bilingüe",
      connected: "Conexión correcta. Este perfil está activo.", connectionFailed: "Error de conexión.", invalidUrl: "La URL base debe ser una URL absoluta válida.", insecureUrl: "La URL base debe usar HTTPS (HTTP solo para localhost).", credentialsUrl: "La URL base no debe contener credenciales.", queryUrl: "La URL base no debe contener consultas ni fragmentos.", privacy: "El texto solo se lee al traducir de forma explícita y se envía únicamente a la API configurada. No se guarda ni se usa para telemetría.", unsupported: "Las extensiones no pueden traducir esta página.", ok: "Aceptar", confirm: "Eliminar", cancel: "Cancelar", saved: "Perfil guardado.", confirmDelete: "¿Eliminar este perfil? Esta acción no se puede deshacer.", deleted: "Perfil eliminado.",
      aboutEyebrow: "Diseñado para leer", aboutTitle: "Traducción sin distracciones", aboutIntro: "Una extensión ligera impulsada por el modelo de IA que elijas. Traduce texto seleccionado o páginas completas sin perder el hilo.", featureFree: "Gratis", featureFreeDesc: "La extensión no cobra suscripción y funciona con tu API configurada.", featureAllInOne: "Traducción IA todo en uno", featureAllInOneDesc: "Gestiona modelos, idiomas, selecciones y páginas completas en un solo lugar.", featureSelection: "Traducción de selección", featureSelectionDesc: "Traduce cualquier fragmento sin salir de la página.", featureBilingual: "Comparación bilingüe", featureBilingualDesc: "Conserva el original junto a la traducción para comparar y aprender.", featureLanguages: "Varios idiomas", featureLanguagesDesc: "Traduce entre numerosos idiomas de uso común.", featureNoAds: "Sin anuncios", featureNoAdsDesc: "Sin publicidad ni ventanas promocionales que interrumpan la lectura.", featurePure: "Limpio", featurePureDesc: "Perfiles locales, sin telemetría y una experiencia centrada en traducir.", featureAccurate: "Preciso", featureAccurateDesc: "Los modelos avanzados comprenden el contexto para conservar el sentido.", featureFluent: "Fluido", featureFluentDesc: "Una redacción legible transmite las ideas con facilidad.", featureNatural: "Natural", featureNaturalDesc: "Expresiones auténticas en lugar de traducciones rígidas palabra por palabra.", aboutClosingTitle: "Creado solo para traducir", aboutClosing: "Rompe las barreras lingüísticas y entiende cualquier contenido de la web."
    }),
    pt: locale({
      localeName: "Português",
      extensionDescription: "Traduza texto selecionado ou páginas da Web com sua API compatível com OpenAI.", actionTitle: "Abrir configurações do tradutor", contextTranslatePage: "Traduzir esta página", contextTranslateSelection: "Traduzir texto selecionado",
      contentTranslating: "Traduzindo…", contentClose: "Fechar", contentRestore: "Restaurar original", contentOpenSettings: "Abrir configurações", contentRunning: "Tradução em andamento", contentFailed: "falhas", contentCancelled: "cancelada", contentRetry: "Tentar falhas novamente", contentSegmentsSent: "segmentos de texto serão enviados", contentRequestLimit: "até {count} solicitações", contentStarting: "Iniciando tradução…", contentNewContent: "Novo conteúdo encontrado. Adicionando tradução…", contentCompletion: "Tradução concluída! {count} segmentos traduzidos (continuaremos monitorando novos conteúdos)", contentPartialCompletion: "Tradução concluída! {count} traduzidos, {failed} falhas (o monitoramento continuará)",
      brandTagline: "Uma ferramenta focada de tradução por IA para qualquer página", uiLanguage: "Idioma da interface", followBrowser: "Seguir o navegador", autoDetect: "Detecção automática", settingsTab: "Configurações", aboutTab: "Sobre", pageNavigation: "Navegação das configurações", save: "Salvar perfil", add: "Adicionar perfil", remove: "Excluir", test: "Testar conexão", active: "Ativo", profiles: "Perfis", profilesEyebrow: "Salvos", editingEyebrow: "Atualizar", createEyebrow: "Configurar", newProfile: "Novo perfil", editProfile: "Editar perfil", noProfiles: "Ainda não há perfis.", name: "Nome", apiKey: "Chave da API", model: "Modelo", language: "Idiomas", source: "Idioma de origem", target: "Idioma de destino", mode: "Modo de tradução", replace: "Substituir original", preserve: "Comparação bilíngue",
      connected: "Conexão bem-sucedida. Este perfil agora está ativo.", connectionFailed: "Falha na conexão.", invalidUrl: "A URL base deve ser uma URL absoluta válida.", insecureUrl: "A URL base deve usar HTTPS (HTTP apenas para localhost).", credentialsUrl: "A URL base não pode conter credenciais.", queryUrl: "A URL base não pode conter consulta ou fragmento.", privacy: "O texto só é lido após uma tradução explícita e enviado apenas à API configurada. Ele não é salvo nem usado para telemetria.", unsupported: "Esta página não pode ser traduzida por extensões do navegador.", ok: "OK", confirm: "Excluir", cancel: "Cancelar", saved: "Perfil salvo.", confirmDelete: "Excluir este perfil? Esta ação não pode ser desfeita.", deleted: "Perfil excluído.",
      aboutEyebrow: "Feito para leitura", aboutTitle: "Tradução sem distrações", aboutIntro: "Uma extensão leve, movida pelo modelo de IA que você escolher. Traduza seleções ou páginas inteiras sem interromper a leitura.", featureFree: "Grátis", featureFreeDesc: "Sem assinatura da extensão; use a API configurada.", featureAllInOne: "Tradução por IA completa", featureAllInOneDesc: "Gerencie modelos, idiomas, seleções e páginas inteiras em um só lugar.", featureSelection: "Tradução de seleção", featureSelectionDesc: "Traduza qualquer trecho sem sair da página.", featureBilingual: "Comparação bilíngue", featureBilingualDesc: "Mantenha o original ao lado da tradução para comparar e estudar.", featureLanguages: "Vários idiomas", featureLanguagesDesc: "Traduza entre diversos idiomas comuns.", featureNoAds: "Sem anúncios", featureNoAdsDesc: "Sem publicidade ou pop-ups promocionais.", featurePure: "Limpo", featurePureDesc: "Perfis locais, sem telemetria e foco total na tradução.", featureAccurate: "Preciso", featureAccurateDesc: "Modelos avançados entendem o contexto e preservam o sentido.", featureFluent: "Fluente", featureFluentDesc: "Frases legíveis fazem as ideias fluírem entre idiomas.", featureNatural: "Natural", featureNaturalDesc: "Expressão autêntica em vez de tradução rígida palavra por palavra.", aboutClosingTitle: "Criado apenas para traduzir", aboutClosing: "Supere barreiras linguísticas e entenda qualquer conteúdo da web."
    }),
    ru: locale({
      localeName: "Русский",
      extensionDescription: "Переводите выделенный текст или веб-страницы через собственный OpenAI-совместимый API.", actionTitle: "Открыть настройки переводчика", contextTranslatePage: "Перевести эту страницу", contextTranslateSelection: "Перевести выделенный текст",
      contentTranslating: "Перевод…", contentClose: "Закрыть", contentRestore: "Восстановить оригинал", contentOpenSettings: "Открыть настройки", contentRunning: "Выполняется перевод", contentFailed: "ошибок", contentCancelled: "отменено", contentRetry: "Повторить ошибки", contentSegmentsSent: "текстовых фрагментов будет отправлено", contentRequestLimit: "до {count} запросов", contentStarting: "Запуск перевода…", contentNewContent: "Найден новый контент. Добавляем перевод…", contentCompletion: "Перевод завершён! Переведено фрагментов: {count} (наблюдение за новым контентом продолжается)", contentPartialCompletion: "Перевод завершён! Переведено: {count}, ошибок: {failed} (наблюдение продолжается)",
      brandTagline: "Специализированный ИИ-переводчик для любых веб-страниц", uiLanguage: "Язык интерфейса", followBrowser: "Как в браузере", autoDetect: "Определять автоматически", settingsTab: "Настройки", aboutTab: "Описание", pageNavigation: "Навигация по настройкам", save: "Сохранить профиль", add: "Добавить профиль", remove: "Удалить", test: "Проверить соединение", active: "Активен", profiles: "Профили", profilesEyebrow: "Сохранённые", editingEyebrow: "Обновление", createEyebrow: "Настройка", newProfile: "Новый профиль", editProfile: "Изменить профиль", noProfiles: "Профилей пока нет.", name: "Название", apiKey: "Ключ API", model: "Модель", language: "Языки", source: "Исходный язык", target: "Целевой язык", mode: "Режим перевода", replace: "Заменить оригинал", preserve: "Двуязычное сравнение",
      connected: "Соединение установлено. Этот профиль теперь активен.", connectionFailed: "Не удалось подключиться.", invalidUrl: "Базовый URL должен быть корректным абсолютным адресом.", insecureUrl: "Базовый URL должен использовать HTTPS (HTTP разрешён только для localhost).", credentialsUrl: "Базовый URL не должен содержать учётные данные.", queryUrl: "Базовый URL не должен содержать запрос или фрагмент.", privacy: "Текст читается только после явного запуска перевода и отправляется лишь в настроенный API. Он не сохраняется и не используется для телеметрии.", unsupported: "Расширения браузера не могут переводить эту страницу.", ok: "ОК", confirm: "Удалить", cancel: "Отмена", saved: "Профиль сохранён.", confirmDelete: "Удалить этот профиль? Действие нельзя отменить.", deleted: "Профиль удалён.",
      aboutEyebrow: "Создано для чтения", aboutTitle: "Перевод без отвлечений", aboutIntro: "Лёгкое расширение на базе выбранной вами ИИ-модели. Переводите выделенный текст или всю страницу, не прерывая чтение.", featureFree: "Бесплатно", featureFreeDesc: "Без подписки на расширение — используется ваш настроенный API.", featureAllInOne: "Всё для ИИ-перевода", featureAllInOneDesc: "Модели, языки, выделения и целые страницы в одном месте.", featureSelection: "Перевод выделения", featureSelectionDesc: "Переводите любой фрагмент, не покидая страницу.", featureBilingual: "Двуязычное сравнение", featureBilingualDesc: "Читайте оригинал рядом с переводом для сравнения и обучения.", featureLanguages: "Много языков", featureLanguagesDesc: "Переводите между множеством распространённых языков.", featureNoAds: "Без рекламы", featureNoAdsDesc: "Никакой рекламы и всплывающих предложений.", featurePure: "Чистота", featurePureDesc: "Локальные профили, отсутствие телеметрии и только перевод.", featureAccurate: "Точно", featureAccurateDesc: "Мощные языковые модели учитывают контекст.", featureFluent: "Плавно", featureFluentDesc: "Удобные формулировки свободно передают мысли между языками.", featureNatural: "Естественно", featureNaturalDesc: "Живая речь вместо жёсткого дословного перевода.", aboutClosingTitle: "Создано только для перевода", aboutClosing: "Легко преодолевайте языковые барьеры и понимайте любой контент в интернете."
    }),
    ar: locale({
      localeName: "العربية",
      extensionDescription: "ترجم النص المحدد أو صفحات الويب باستخدام واجهة API المتوافقة مع OpenAI الخاصة بك.", actionTitle: "فتح إعدادات المترجم", contextTranslatePage: "ترجمة هذه الصفحة", contextTranslateSelection: "ترجمة النص المحدد",
      contentTranslating: "جارٍ الترجمة…", contentClose: "إغلاق", contentRestore: "استعادة الأصل", contentOpenSettings: "فتح الإعدادات", contentRunning: "الترجمة جارية", contentFailed: "فشل", contentCancelled: "أُلغيت", contentRetry: "إعادة محاولة العناصر الفاشلة", contentSegmentsSent: "مقاطع نصية سيتم إرسالها", contentRequestLimit: "حتى {count} طلبًا", contentStarting: "جارٍ بدء الترجمة…", contentNewContent: "تم العثور على محتوى جديد. جارٍ إضافة الترجمة…", contentCompletion: "اكتملت الترجمة! تمت ترجمة {count} مقطعًا (ستستمر مراقبة المحتوى الجديد)", contentPartialCompletion: "اكتملت الترجمة! تمت ترجمة {count} وفشل {failed} (ستستمر المراقبة)",
      brandTagline: "أداة ترجمة بالذكاء الاصطناعي لكل صفحة ويب", uiLanguage: "لغة الواجهة", followBrowser: "اتباع لغة المتصفح", autoDetect: "اكتشاف تلقائي", settingsTab: "الإعدادات", aboutTab: "حول", pageNavigation: "التنقل في الإعدادات", save: "حفظ الملف", add: "إضافة ملف", remove: "حذف", test: "اختبار الاتصال", active: "نشط", profiles: "الملفات", profilesEyebrow: "محفوظة", editingEyebrow: "تحديث", createEyebrow: "إعداد", newProfile: "ملف جديد", editProfile: "تعديل الملف", noProfiles: "لا توجد ملفات بعد.", name: "الاسم", apiKey: "مفتاح API", model: "النموذج", language: "اللغات", source: "لغة المصدر", target: "اللغة الهدف", mode: "وضع الترجمة", replace: "استبدال الأصل", preserve: "مقارنة ثنائية اللغة",
      connected: "تم الاتصال وأصبح هذا الملف نشطًا.", connectionFailed: "فشل الاتصال.", invalidUrl: "يجب أن يكون عنوان Base URL مطلقًا وصحيحًا.", insecureUrl: "يجب أن يستخدم Base URL بروتوكول HTTPS (يسمح HTTP لـ localhost فقط).", credentialsUrl: "يجب ألا يتضمن Base URL بيانات اعتماد.", queryUrl: "يجب ألا يتضمن Base URL استعلامًا أو جزءًا.", privacy: "لا يُقرأ النص إلا بعد طلب الترجمة صراحةً ويُرسل فقط إلى API الذي أعددته. لا يُحفظ ولا يُستخدم للقياس.", unsupported: "لا تستطيع إضافات المتصفح ترجمة هذه الصفحة.", ok: "موافق", confirm: "حذف", cancel: "إلغاء", saved: "تم حفظ الملف.", confirmDelete: "هل تريد حذف هذا الملف؟ لا يمكن التراجع.", deleted: "تم حذف الملف.",
      aboutEyebrow: "مصمم للقراءة", aboutTitle: "ترجمة بلا تشتيت", aboutIntro: "إضافة خفيفة تعمل بنموذج الذكاء الاصطناعي الذي تختاره. ترجم النص المحدد أو الصفحة كاملة دون مغادرة قراءتك.", featureFree: "مجاني", featureFreeDesc: "لا رسوم اشتراك للإضافة وتعمل مع API الذي أعددته.", featureAllInOne: "ترجمة متكاملة بالذكاء الاصطناعي", featureAllInOneDesc: "أدر النماذج واللغات والنص المحدد والصفحات الكاملة في مكان واحد.", featureSelection: "ترجمة النص المحدد", featureSelectionDesc: "ترجم أي مقطع دون مغادرة الصفحة.", featureBilingual: "مقارنة ثنائية اللغة", featureBilingualDesc: "احتفظ بالأصل بجانب الترجمة للمقارنة والتعلم.", featureLanguages: "لغات متعددة", featureLanguagesDesc: "ترجم بين مجموعة واسعة من اللغات الشائعة.", featureNoAds: "بلا إعلانات", featureNoAdsDesc: "لا إعلانات أو نوافذ ترويجية تقطع القراءة.", featurePure: "نقي", featurePureDesc: "ملفات محلية، بلا قياس، وتركيز كامل على الترجمة.", featureAccurate: "دقيق", featureAccurateDesc: "تفهم النماذج القوية السياق لتنقل المعنى بدقة.", featureFluent: "سلس", featureFluentDesc: "صياغة سهلة القراءة تنقل الأفكار بسلاسة.", featureNatural: "طبيعي", featureNaturalDesc: "تعبير أصيل بدل الترجمة الحرفية الجامدة.", aboutClosingTitle: "مصمم للترجمة فقط", aboutClosing: "تجاوز حواجز اللغة وافهم أي محتوى على الويب."
    }),
    it: locale({
      localeName: "Italiano",
      extensionDescription: "Traduci testo selezionato o pagine web con la tua API compatibile con OpenAI.", actionTitle: "Apri le impostazioni del traduttore", contextTranslatePage: "Traduci questa pagina", contextTranslateSelection: "Traduci il testo selezionato",
      contentTranslating: "Traduzione…", contentClose: "Chiudi", contentRestore: "Ripristina originale", contentOpenSettings: "Apri impostazioni", contentRunning: "Traduzione in corso", contentFailed: "non riusciti", contentCancelled: "annullata", contentRetry: "Riprova elementi non riusciti", contentSegmentsSent: "segmenti di testo saranno inviati", contentRequestLimit: "fino a {count} richieste", contentStarting: "Avvio della traduzione…", contentNewContent: "Trovato nuovo contenuto. Aggiunta della traduzione…", contentCompletion: "Traduzione completata! {count} segmenti tradotti (continueremo a monitorare nuovi contenuti)", contentPartialCompletion: "Traduzione completata! {count} tradotti, {failed} non riusciti (il monitoraggio continua)",
      brandTagline: "Uno strumento di traduzione IA dedicato a ogni pagina web", uiLanguage: "Lingua dell’interfaccia", followBrowser: "Segui il browser", autoDetect: "Rilevamento automatico", settingsTab: "Impostazioni", aboutTab: "Informazioni", pageNavigation: "Navigazione impostazioni", save: "Salva profilo", add: "Aggiungi profilo", remove: "Elimina", test: "Verifica connessione", active: "Attivo", profiles: "Profili", profilesEyebrow: "Salvati", editingEyebrow: "Aggiorna", createEyebrow: "Configura", newProfile: "Nuovo profilo", editProfile: "Modifica profilo", noProfiles: "Nessun profilo.", name: "Nome", apiKey: "Chiave API", model: "Modello", language: "Lingue", source: "Lingua di origine", target: "Lingua di destinazione", mode: "Modalità di traduzione", replace: "Sostituisci originale", preserve: "Confronto bilingue",
      connected: "Connessione riuscita. Questo profilo è ora attivo.", connectionFailed: "Connessione non riuscita.", invalidUrl: "Il Base URL deve essere un URL assoluto valido.", insecureUrl: "Il Base URL deve usare HTTPS (HTTP solo per localhost).", credentialsUrl: "Il Base URL non deve contenere credenziali.", queryUrl: "Il Base URL non deve contenere query o frammenti.", privacy: "Il testo viene letto solo dopo una traduzione esplicita e inviato esclusivamente all’API configurata. Non viene salvato né usato per telemetria.", unsupported: "Questa pagina non può essere tradotta dalle estensioni del browser.", ok: "OK", confirm: "Elimina", cancel: "Annulla", saved: "Profilo salvato.", confirmDelete: "Eliminare questo profilo? L’azione non può essere annullata.", deleted: "Profilo eliminato.",
      aboutEyebrow: "Pensato per leggere", aboutTitle: "Traduzione senza distrazioni", aboutIntro: "Un’estensione leggera basata sul modello IA che preferisci. Traduci una selezione o un’intera pagina senza interrompere la lettura.", featureFree: "Gratis", featureFreeDesc: "Nessun abbonamento all’estensione; usa l’API configurata.", featureAllInOne: "Traduzione IA tutto in uno", featureAllInOneDesc: "Gestisci modelli, lingue, selezioni e pagine intere in un solo posto.", featureSelection: "Traduzione della selezione", featureSelectionDesc: "Traduci qualsiasi passaggio senza lasciare la pagina.", featureBilingual: "Confronto bilingue", featureBilingualDesc: "Conserva l’originale accanto alla traduzione per confrontare e studiare.", featureLanguages: "Più lingue", featureLanguagesDesc: "Traduci tra numerose lingue comuni.", featureNoAds: "Senza pubblicità", featureNoAdsDesc: "Niente annunci o popup promozionali.", featurePure: "Essenziale", featurePureDesc: "Profili locali, nessuna telemetria e attenzione solo alla traduzione.", featureAccurate: "Accurato", featureAccurateDesc: "I modelli avanzati comprendono il contesto e conservano il significato.", featureFluent: "Scorrevole", featureFluentDesc: "Frasi leggibili fanno fluire le idee tra le lingue.", featureNatural: "Naturale", featureNaturalDesc: "Espressioni autentiche invece di rigide traduzioni parola per parola.", aboutClosingTitle: "Creato solo per tradurre", aboutClosing: "Supera le barriere linguistiche e comprendi qualsiasi contenuto sul Web."
    }),
    th: locale({
      localeName: "ไทย",
      extensionDescription: "แปลข้อความที่เลือกหรือหน้าเว็บด้วย API ที่เข้ากันได้กับ OpenAI ของคุณ", actionTitle: "เปิดการตั้งค่าตัวแปล", contextTranslatePage: "แปลหน้านี้", contextTranslateSelection: "แปลข้อความที่เลือก",
      contentTranslating: "กำลังแปล…", contentClose: "ปิด", contentRestore: "คืนค่าต้นฉบับ", contentOpenSettings: "เปิดการตั้งค่า", contentRunning: "กำลังดำเนินการแปล", contentFailed: "ล้มเหลว", contentCancelled: "ยกเลิกแล้ว", contentRetry: "ลองรายการที่ล้มเหลวอีกครั้ง", contentSegmentsSent: "ส่วนข้อความจะถูกส่ง", contentRequestLimit: "สูงสุด {count} คำขอ", contentStarting: "กำลังเริ่มแปล…", contentNewContent: "พบเนื้อหาใหม่ กำลังเพิ่มคำแปล…", contentCompletion: "แปลเสร็จแล้ว! แปลข้อความ {count} ส่วน (จะติดตามเนื้อหาใหม่ต่อไป)", contentPartialCompletion: "แปลเสร็จแล้ว! แปลสำเร็จ {count} ส่วน ล้มเหลว {failed} ส่วน (จะติดตามต่อไป)",
      brandTagline: "เครื่องมือแปลด้วย AI สำหรับทุกหน้าเว็บ", uiLanguage: "ภาษาของส่วนติดต่อ", followBrowser: "ตามภาษาของเบราว์เซอร์", autoDetect: "ตรวจจับอัตโนมัติ", settingsTab: "การตั้งค่า", aboutTab: "เกี่ยวกับ", pageNavigation: "การนำทางการตั้งค่า", save: "บันทึกโปรไฟล์", add: "เพิ่มโปรไฟล์", remove: "ลบ", test: "ทดสอบการเชื่อมต่อ", active: "ใช้งานอยู่", profiles: "โปรไฟล์", profilesEyebrow: "บันทึกแล้ว", editingEyebrow: "อัปเดต", createEyebrow: "กำหนดค่า", newProfile: "โปรไฟล์ใหม่", editProfile: "แก้ไขโปรไฟล์", noProfiles: "ยังไม่มีโปรไฟล์", name: "ชื่อ", apiKey: "คีย์ API", model: "โมเดล", language: "ภาษา", source: "ภาษาต้นทาง", target: "ภาษาเป้าหมาย", mode: "โหมดการแปล", replace: "แทนที่ต้นฉบับ", preserve: "เปรียบเทียบสองภาษา",
      connected: "เชื่อมต่อสำเร็จและเปิดใช้โปรไฟล์นี้แล้ว", connectionFailed: "การเชื่อมต่อล้มเหลว", invalidUrl: "Base URL ต้องเป็น URL แบบสมบูรณ์ที่ถูกต้อง", insecureUrl: "Base URL ต้องใช้ HTTPS (อนุญาต HTTP เฉพาะ localhost)", credentialsUrl: "Base URL ต้องไม่มีข้อมูลรับรอง", queryUrl: "Base URL ต้องไม่มีคำค้นหรือส่วนย่อย", privacy: "ระบบจะอ่านข้อความเมื่อคุณสั่งแปลเท่านั้น และส่งไปยัง API ที่ตั้งค่าไว้โดยไม่บันทึกหรือเก็บข้อมูลการใช้งาน", unsupported: "ส่วนขยายเบราว์เซอร์ไม่สามารถแปลหน้านี้ได้", ok: "ตกลง", confirm: "ลบ", cancel: "ยกเลิก", saved: "บันทึกโปรไฟล์แล้ว", confirmDelete: "ลบโปรไฟล์นี้หรือไม่? ไม่สามารถย้อนกลับได้", deleted: "ลบโปรไฟล์แล้ว",
      aboutEyebrow: "ออกแบบมาเพื่อการอ่าน", aboutTitle: "แปลอย่างไร้สิ่งรบกวน", aboutIntro: "ส่วนขยายขนาดเล็กที่ใช้โมเดล AI ที่คุณเลือก แปลข้อความที่เลือกหรือทั้งหน้าโดยไม่ขัดจังหวะการอ่าน", featureFree: "ฟรี", featureFreeDesc: "ไม่มีค่าสมัครสมาชิกส่วนขยายและใช้ API ที่คุณตั้งค่า", featureAllInOne: "การแปล AI ครบวงจร", featureAllInOneDesc: "จัดการโมเดล ภาษา ข้อความที่เลือก และทั้งหน้าในที่เดียว", featureSelection: "แปลข้อความที่เลือก", featureSelectionDesc: "แปลข้อความใดก็ได้โดยไม่ออกจากหน้า", featureBilingual: "เปรียบเทียบสองภาษา", featureBilingualDesc: "เก็บต้นฉบับไว้ข้างคำแปลเพื่อเปรียบเทียบและเรียนรู้", featureLanguages: "หลายภาษา", featureLanguagesDesc: "แปลระหว่างภาษาที่ใช้กันทั่วไปมากมาย", featureNoAds: "ไม่มีโฆษณา", featureNoAdsDesc: "ไม่มีโฆษณาหรือป๊อปอัปส่งเสริมการขาย", featurePure: "เรียบง่าย", featurePureDesc: "โปรไฟล์ในเครื่อง ไม่มีการติดตาม และมุ่งเน้นการแปล", featureAccurate: "แม่นยำ", featureAccurateDesc: "โมเดลภาษาที่ทรงพลังเข้าใจบริบทและรักษาความหมาย", featureFluent: "ลื่นไหล", featureFluentDesc: "ถ้อยคำที่อ่านง่ายช่วยถ่ายทอดแนวคิดระหว่างภาษา", featureNatural: "เป็นธรรมชาติ", featureNaturalDesc: "เน้นภาษาที่แท้จริงแทนการแปลคำต่อคำ", aboutClosingTitle: "สร้างมาเพื่อการแปลเท่านั้น", aboutClosing: "ก้าวข้ามกำแพงภาษาและเข้าใจทุกเนื้อหาบนเว็บ"
    }),
    vi: locale({
      localeName: "Tiếng Việt",
      extensionDescription: "Dịch văn bản đã chọn hoặc trang web bằng API tương thích OpenAI của bạn.", actionTitle: "Mở cài đặt trình dịch", contextTranslatePage: "Dịch trang này", contextTranslateSelection: "Dịch văn bản đã chọn",
      contentTranslating: "Đang dịch…", contentClose: "Đóng", contentRestore: "Khôi phục bản gốc", contentOpenSettings: "Mở cài đặt", contentRunning: "Đang tiến hành dịch", contentFailed: "thất bại", contentCancelled: "đã hủy", contentRetry: "Thử lại mục thất bại", contentSegmentsSent: "đoạn văn bản sẽ được gửi", contentRequestLimit: "tối đa {count} yêu cầu", contentStarting: "Đang bắt đầu dịch…", contentNewContent: "Đã tìm thấy nội dung mới. Đang thêm bản dịch…", contentCompletion: "Dịch hoàn tất! Đã dịch {count} đoạn văn bản (tiếp tục theo dõi nội dung mới)", contentPartialCompletion: "Dịch hoàn tất! Đã dịch {count} đoạn, {failed} đoạn thất bại (tiếp tục theo dõi)",
      brandTagline: "Công cụ dịch AI tập trung cho mọi trang web", uiLanguage: "Ngôn ngữ giao diện", followBrowser: "Theo trình duyệt", autoDetect: "Tự động nhận diện", settingsTab: "Cài đặt", aboutTab: "Giới thiệu", pageNavigation: "Điều hướng cài đặt", save: "Lưu hồ sơ", add: "Thêm hồ sơ", remove: "Xóa", test: "Kiểm tra kết nối", active: "Đang dùng", profiles: "Hồ sơ", profilesEyebrow: "Đã lưu", editingEyebrow: "Cập nhật", createEyebrow: "Cấu hình", newProfile: "Hồ sơ mới", editProfile: "Sửa hồ sơ", noProfiles: "Chưa có hồ sơ.", name: "Tên", apiKey: "Khóa API", model: "Mô hình", language: "Ngôn ngữ", source: "Ngôn ngữ nguồn", target: "Ngôn ngữ đích", mode: "Chế độ dịch", replace: "Thay thế bản gốc", preserve: "Đối chiếu song ngữ",
      connected: "Kết nối thành công. Hồ sơ này hiện đang hoạt động.", connectionFailed: "Kết nối thất bại.", invalidUrl: "Base URL phải là URL tuyệt đối hợp lệ.", insecureUrl: "Base URL phải dùng HTTPS (HTTP chỉ dành cho localhost).", credentialsUrl: "Base URL không được chứa thông tin đăng nhập.", queryUrl: "Base URL không được chứa truy vấn hoặc phân mảnh.", privacy: "Văn bản chỉ được đọc khi bạn chủ động dịch và chỉ gửi đến API đã cấu hình. Nội dung không được lưu hoặc dùng cho đo lường.", unsupported: "Tiện ích trình duyệt không thể dịch trang này.", ok: "OK", confirm: "Xóa", cancel: "Hủy", saved: "Đã lưu hồ sơ.", confirmDelete: "Xóa hồ sơ này? Không thể hoàn tác.", deleted: "Đã xóa hồ sơ.",
      aboutEyebrow: "Thiết kế cho việc đọc", aboutTitle: "Dịch không xao nhãng", aboutIntro: "Tiện ích nhẹ chạy bằng mô hình AI bạn chọn. Dịch đoạn đã chọn hoặc toàn bộ trang mà không làm gián đoạn việc đọc.", featureFree: "Miễn phí", featureFreeDesc: "Không mất phí đăng ký tiện ích; sử dụng API bạn cấu hình.", featureAllInOne: "Dịch AI tất cả trong một", featureAllInOneDesc: "Quản lý mô hình, ngôn ngữ, đoạn chọn và toàn trang tại một nơi.", featureSelection: "Dịch đoạn chọn", featureSelectionDesc: "Dịch bất kỳ đoạn nào mà không rời trang.", featureBilingual: "Đối chiếu song ngữ", featureBilingualDesc: "Giữ bản gốc cạnh bản dịch để đối chiếu và học tập.", featureLanguages: "Nhiều ngôn ngữ", featureLanguagesDesc: "Dịch giữa nhiều ngôn ngữ phổ biến.", featureNoAds: "Không quảng cáo", featureNoAdsDesc: "Không quảng cáo hoặc cửa sổ tiếp thị làm gián đoạn.", featurePure: "Thuần khiết", featurePureDesc: "Hồ sơ cục bộ, không đo lường và chỉ tập trung vào dịch thuật.", featureAccurate: "Chính xác", featureAccurateDesc: "Mô hình mạnh hiểu ngữ cảnh để giữ đúng ý nghĩa.", featureFluent: "Trôi chảy", featureFluentDesc: "Cách diễn đạt dễ đọc giúp ý tưởng chuyển đổi tự nhiên.", featureNatural: "Tự nhiên", featureNaturalDesc: "Ưu tiên ngôn ngữ chân thực thay vì dịch cứng từng từ.", aboutClosingTitle: "Chỉ được tạo ra để dịch", aboutClosing: "Dễ dàng vượt qua rào cản ngôn ngữ và hiểu mọi nội dung trên web."
    }),
    id: locale({
      localeName: "Bahasa Indonesia",
      extensionDescription: "Terjemahkan teks pilihan atau halaman web dengan API kompatibel OpenAI milik Anda.", actionTitle: "Buka pengaturan penerjemah", contextTranslatePage: "Terjemahkan halaman ini", contextTranslateSelection: "Terjemahkan teks pilihan",
      contentTranslating: "Menerjemahkan…", contentClose: "Tutup", contentRestore: "Pulihkan teks asli", contentOpenSettings: "Buka pengaturan", contentRunning: "Penerjemahan berlangsung", contentFailed: "gagal", contentCancelled: "dibatalkan", contentRetry: "Coba lagi yang gagal", contentSegmentsSent: "segmen teks akan dikirim", contentRequestLimit: "hingga {count} permintaan", contentStarting: "Memulai penerjemahan…", contentNewContent: "Konten baru ditemukan. Menambahkan terjemahan…", contentCompletion: "Penerjemahan selesai! {count} segmen diterjemahkan (tetap memantau konten baru)", contentPartialCompletion: "Penerjemahan selesai! {count} diterjemahkan, {failed} gagal (pemantauan berlanjut)",
      brandTagline: "Alat terjemahan AI terfokus untuk setiap halaman web", uiLanguage: "Bahasa antarmuka", followBrowser: "Ikuti browser", autoDetect: "Deteksi otomatis", settingsTab: "Pengaturan", aboutTab: "Tentang", pageNavigation: "Navigasi pengaturan", save: "Simpan profil", add: "Tambah profil", remove: "Hapus", test: "Uji koneksi", active: "Aktif", profiles: "Profil", profilesEyebrow: "Tersimpan", editingEyebrow: "Perbarui", createEyebrow: "Konfigurasi", newProfile: "Profil baru", editProfile: "Edit profil", noProfiles: "Belum ada profil.", name: "Nama", apiKey: "Kunci API", model: "Model", language: "Bahasa", source: "Bahasa sumber", target: "Bahasa tujuan", mode: "Mode terjemahan", replace: "Ganti teks asli", preserve: "Perbandingan dwibahasa",
      connected: "Koneksi berhasil. Profil ini sekarang aktif.", connectionFailed: "Koneksi gagal.", invalidUrl: "Base URL harus berupa URL absolut yang valid.", insecureUrl: "Base URL harus menggunakan HTTPS (HTTP hanya untuk localhost).", credentialsUrl: "Base URL tidak boleh berisi kredensial.", queryUrl: "Base URL tidak boleh berisi kueri atau fragmen.", privacy: "Teks hanya dibaca setelah Anda meminta terjemahan dan hanya dikirim ke API yang dikonfigurasi. Teks tidak disimpan atau digunakan untuk telemetri.", unsupported: "Halaman ini tidak dapat diterjemahkan oleh ekstensi browser.", ok: "OK", confirm: "Hapus", cancel: "Batal", saved: "Profil disimpan.", confirmDelete: "Hapus profil ini? Tindakan ini tidak dapat dibatalkan.", deleted: "Profil dihapus.",
      aboutEyebrow: "Dirancang untuk membaca", aboutTitle: "Terjemahan tanpa gangguan", aboutIntro: "Ekstensi ringan yang menggunakan model AI pilihan Anda. Terjemahkan teks terpilih atau seluruh halaman tanpa mengganggu bacaan.", featureFree: "Gratis", featureFreeDesc: "Tidak ada biaya langganan ekstensi; gunakan API yang Anda atur.", featureAllInOne: "Terjemahan AI terpadu", featureAllInOneDesc: "Kelola model, bahasa, pilihan teks, dan seluruh halaman di satu tempat.", featureSelection: "Terjemahkan pilihan", featureSelectionDesc: "Terjemahkan bagian mana pun tanpa meninggalkan halaman.", featureBilingual: "Perbandingan dwibahasa", featureBilingualDesc: "Pertahankan teks asli di samping terjemahan untuk membandingkan dan belajar.", featureLanguages: "Beragam bahasa", featureLanguagesDesc: "Terjemahkan berbagai bahasa yang umum digunakan.", featureNoAds: "Tanpa iklan", featureNoAdsDesc: "Tanpa iklan atau pop-up promosi yang mengganggu.", featurePure: "Bersih", featurePureDesc: "Profil lokal, tanpa telemetri, dan fokus hanya pada terjemahan.", featureAccurate: "Akurat", featureAccurateDesc: "Model yang andal memahami konteks dan menjaga makna.", featureFluent: "Lancar", featureFluentDesc: "Susunan yang mudah dibaca membuat gagasan mengalir antarbahasa.", featureNatural: "Alami", featureNaturalDesc: "Ungkapan autentik, bukan terjemahan kata demi kata yang kaku.", aboutClosingTitle: "Dibuat hanya untuk menerjemahkan", aboutClosing: "Atasi hambatan bahasa dan pahami setiap konten di web."
    }),
    hi: locale({
      localeName: "हिन्दी",
      extensionDescription: "अपने OpenAI-संगत API से चुने हुए पाठ या वेबपेज का अनुवाद करें।", actionTitle: "अनुवादक सेटिंग खोलें", contextTranslatePage: "इस पृष्ठ का अनुवाद करें", contextTranslateSelection: "चुने हुए पाठ का अनुवाद करें",
      contentTranslating: "अनुवाद हो रहा है…", contentClose: "बंद करें", contentRestore: "मूल पाठ पुनर्स्थापित करें", contentOpenSettings: "सेटिंग खोलें", contentRunning: "अनुवाद जारी है", contentFailed: "विफल", contentCancelled: "रद्द", contentRetry: "विफल आइटम फिर आज़माएँ", contentSegmentsSent: "पाठ खंड भेजे जाएँगे", contentRequestLimit: "अधिकतम {count} अनुरोध", contentStarting: "अनुवाद शुरू हो रहा है…", contentNewContent: "नई सामग्री मिली। अनुवाद जोड़ा जा रहा है…", contentCompletion: "अनुवाद पूरा! {count} पाठ खंड अनुवादित (नई सामग्री की निगरानी जारी रहेगी)", contentPartialCompletion: "अनुवाद पूरा! {count} अनुवादित, {failed} विफल (निगरानी जारी रहेगी)",
      brandTagline: "हर वेबपेज के लिए केंद्रित AI अनुवाद उपकरण", uiLanguage: "इंटरफ़ेस भाषा", followBrowser: "ब्राउज़र के अनुसार", autoDetect: "स्वतः पहचान", settingsTab: "सेटिंग", aboutTab: "परिचय", pageNavigation: "सेटिंग नेविगेशन", save: "प्रोफ़ाइल सहेजें", add: "प्रोफ़ाइल जोड़ें", remove: "हटाएँ", test: "कनेक्शन जाँचें", active: "सक्रिय", profiles: "प्रोफ़ाइल", profilesEyebrow: "सहेजी गई", editingEyebrow: "अपडेट", createEyebrow: "कॉन्फ़िगर", newProfile: "नई प्रोफ़ाइल", editProfile: "प्रोफ़ाइल संपादित करें", noProfiles: "अभी कोई प्रोफ़ाइल नहीं है।", name: "नाम", apiKey: "API कुंजी", model: "मॉडल", language: "भाषाएँ", source: "स्रोत भाषा", target: "लक्ष्य भाषा", mode: "अनुवाद मोड", replace: "मूल पाठ बदलें", preserve: "द्विभाषी तुलना",
      connected: "कनेक्शन सफल। यह प्रोफ़ाइल अब सक्रिय है।", connectionFailed: "कनेक्शन विफल।", invalidUrl: "Base URL एक मान्य पूर्ण URL होना चाहिए।", insecureUrl: "Base URL में HTTPS होना चाहिए (HTTP केवल localhost के लिए)।", credentialsUrl: "Base URL में क्रेडेंशियल नहीं होने चाहिए।", queryUrl: "Base URL में क्वेरी या फ़्रैगमेंट नहीं होना चाहिए।", privacy: "पाठ केवल आपके स्पष्ट अनुवाद अनुरोध के बाद पढ़ा जाता है और सिर्फ़ कॉन्फ़िगर API को भेजा जाता है। इसे सहेजा या टेलीमेट्री के लिए उपयोग नहीं किया जाता।", unsupported: "ब्राउज़र एक्सटेंशन इस पृष्ठ का अनुवाद नहीं कर सकते।", ok: "ठीक", confirm: "हटाएँ", cancel: "रद्द करें", saved: "प्रोफ़ाइल सहेजी गई।", confirmDelete: "यह प्रोफ़ाइल हटाएँ? इसे वापस नहीं किया जा सकता।", deleted: "प्रोफ़ाइल हटा दी गई।",
      aboutEyebrow: "पढ़ने के लिए बनाया गया", aboutTitle: "बिना बाधा अनुवाद", aboutIntro: "आपके चुने AI मॉडल से चलने वाला हल्का एक्सटेंशन। पढ़ना छोड़े बिना चुना हुआ पाठ या पूरा पृष्ठ अनुवाद करें।", featureFree: "मुफ़्त", featureFreeDesc: "एक्सटेंशन की सदस्यता फीस नहीं; अपने कॉन्फ़िगर API का उपयोग करें।", featureAllInOne: "संपूर्ण AI अनुवाद", featureAllInOneDesc: "मॉडल, भाषाएँ, चयन और पूरे पृष्ठ का अनुवाद एक जगह प्रबंधित करें।", featureSelection: "चयन अनुवाद", featureSelectionDesc: "पृष्ठ छोड़े बिना किसी भी अंश का अनुवाद करें।", featureBilingual: "द्विभाषी तुलना", featureBilingualDesc: "तुलना और सीखने के लिए मूल और अनुवाद साथ रखें।", featureLanguages: "कई भाषाएँ", featureLanguagesDesc: "अनेक प्रचलित भाषाओं के बीच अनुवाद करें।", featureNoAds: "विज्ञापन-मुक्त", featureNoAdsDesc: "कोई विज्ञापन या प्रचार पॉप-अप नहीं।", featurePure: "शुद्ध", featurePureDesc: "स्थानीय प्रोफ़ाइल, कोई टेलीमेट्री नहीं और केवल अनुवाद पर ध्यान।", featureAccurate: "सटीक", featureAccurateDesc: "सक्षम मॉडल संदर्भ समझकर अर्थ सुरक्षित रखते हैं।", featureFluent: "प्रवाहपूर्ण", featureFluentDesc: "पढ़ने योग्य भाषा विचारों को सहजता से पहुँचाती है।", featureNatural: "स्वाभाविक", featureNaturalDesc: "कठोर शब्दशः आउटपुट के बजाय प्रामाणिक अभिव्यक्ति।", aboutClosingTitle: "केवल अनुवाद के लिए निर्मित", aboutClosing: "भाषा की बाधाएँ आसानी से तोड़ें और वेब की हर सामग्री समझें।"
    }),
    tr: locale({
      localeName: "Türkçe",
      extensionDescription: "Seçili metni veya web sayfalarını kendi OpenAI uyumlu API’nizle çevirin.", actionTitle: "Çevirmen ayarlarını aç", contextTranslatePage: "Bu sayfayı çevir", contextTranslateSelection: "Seçili metni çevir",
      contentTranslating: "Çevriliyor…", contentClose: "Kapat", contentRestore: "Orijinali geri yükle", contentOpenSettings: "Ayarları aç", contentRunning: "Çeviri sürüyor", contentFailed: "başarısız", contentCancelled: "iptal edildi", contentRetry: "Başarısızları yeniden dene", contentSegmentsSent: "metin bölümü gönderilecek", contentRequestLimit: "en fazla {count} istek", contentStarting: "Çeviri başlatılıyor…", contentNewContent: "Yeni içerik bulundu. Çeviri ekleniyor…", contentCompletion: "Çeviri tamamlandı! {count} metin bölümü çevrildi (yeni içerik izlenmeye devam edecek)", contentPartialCompletion: "Çeviri tamamlandı! {count} çevrildi, {failed} başarısız (izleme sürecek)",
      brandTagline: "Her web sayfası için odaklanmış yapay zekâ çeviri aracı", uiLanguage: "Arayüz dili", followBrowser: "Tarayıcıyı izle", autoDetect: "Otomatik algıla", settingsTab: "Ayarlar", aboutTab: "Hakkında", pageNavigation: "Ayarlar gezintisi", save: "Profili kaydet", add: "Profil ekle", remove: "Sil", test: "Bağlantıyı sına", active: "Etkin", profiles: "Profiller", profilesEyebrow: "Kaydedilenler", editingEyebrow: "Güncelle", createEyebrow: "Yapılandır", newProfile: "Yeni profil", editProfile: "Profili düzenle", noProfiles: "Henüz profil yok.", name: "Ad", apiKey: "API anahtarı", model: "Model", language: "Diller", source: "Kaynak dil", target: "Hedef dil", mode: "Çeviri modu", replace: "Orijinali değiştir", preserve: "İki dilli karşılaştırma",
      connected: "Bağlantı başarılı. Bu profil artık etkin.", connectionFailed: "Bağlantı başarısız.", invalidUrl: "Base URL geçerli bir mutlak URL olmalıdır.", insecureUrl: "Base URL HTTPS kullanmalıdır (HTTP yalnızca localhost için).", credentialsUrl: "Base URL kimlik bilgisi içermemelidir.", queryUrl: "Base URL sorgu veya parça içermemelidir.", privacy: "Metin yalnızca açıkça çeviri istediğinizde okunur ve sadece yapılandırılmış API’ye gönderilir. Kaydedilmez veya telemetri için kullanılmaz.", unsupported: "Tarayıcı uzantıları bu sayfayı çeviremez.", ok: "Tamam", confirm: "Sil", cancel: "İptal", saved: "Profil kaydedildi.", confirmDelete: "Bu profil silinsin mi? Bu işlem geri alınamaz.", deleted: "Profil silindi.",
      aboutEyebrow: "Okumak için tasarlandı", aboutTitle: "Dikkat dağıtmayan çeviri", aboutIntro: "Seçtiğiniz yapay zekâ modeliyle çalışan hafif bir uzantı. Okumadan kopmadan seçili metni veya tüm sayfayı çevirin.", featureFree: "Ücretsiz", featureFreeDesc: "Uzantı aboneliği yoktur; yapılandırdığınız API ile çalışır.", featureAllInOne: "Hepsi bir arada yapay zekâ çevirisi", featureAllInOneDesc: "Modelleri, dilleri, seçimleri ve tam sayfa çevirisini tek yerde yönetin.", featureSelection: "Seçimi çevir", featureSelectionDesc: "Sayfadan ayrılmadan istediğiniz bölümü çevirin.", featureBilingual: "İki dilli karşılaştırma", featureBilingualDesc: "Karşılaştırmak ve öğrenmek için orijinali çevirinin yanında tutun.", featureLanguages: "Çoklu dil", featureLanguagesDesc: "Yaygın kullanılan birçok dil arasında çeviri yapın.", featureNoAds: "Reklamsız", featureNoAdsDesc: "Okumayı bölen reklam veya tanıtım pencereleri yok.", featurePure: "Sade", featurePureDesc: "Yerel profiller, telemetri yok ve yalnızca çeviriye odaklanır.", featureAccurate: "Doğru", featureAccurateDesc: "Güçlü modeller bağlamı anlayarak anlamı korur.", featureFluent: "Akıcı", featureFluentDesc: "Okunabilir ifadeler fikirleri diller arasında akıcı biçimde taşır.", featureNatural: "Doğal", featureNaturalDesc: "Katı kelimesi kelimesine çıktı yerine gerçekçi anlatım.", aboutClosingTitle: "Yalnızca çeviri için üretildi", aboutClosing: "Dil engellerini kolayca aşın ve webdeki her içeriği anlayın."
    })
  };
}
