import { mkdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const root = new URL("../", import.meta.url);
const browserLocaleNames = {
  en: "en", "zh-CN": "zh_CN", "zh-TW": "zh_TW", ja: "ja", ko: "ko", fr: "fr", de: "de", es: "es",
  pt: "pt_BR", ru: "ru", ar: "ar", it: "it", th: "th", vi: "vi", id: "id", hi: "hi", tr: "tr"
};
const browserFields = {
  extensionName: "title",
  extensionShortName: "shortName",
  extensionDescription: "extensionDescription",
  actionTitle: "actionTitle",
  contextTranslatePage: "contextTranslatePage",
  contextTranslateSelection: "contextTranslateSelection",
  unsupportedPage: "unsupported"
};
const contentFields = {
  translating: "contentTranslating", cancel: "cancel", close: "contentClose", restore: "contentRestore", openSettings: "contentOpenSettings",
  running: "contentRunning", failed: "contentFailed", cancelled: "contentCancelled", retry: "contentRetry", nodes: "contentSegmentsSent",
  requestLimit: "contentRequestLimit", starting: "contentStarting", newContent: "contentNewContent", completion: "contentCompletion", partialCompletion: "contentPartialCompletion"
};
const optionsFields = {
  translateTab: "translateTab", translatorEyebrow: "translatorEyebrow", translatorTitle: "translatorTitle", translationInput: "translationInput",
  inputPlaceholder: "inputPlaceholder", characterCount: "characterCount", clear: "clear", translateAction: "translateAction",
  translationInProgress: "translationInProgress", modelRequired: "modelRequired", translationFailed: "translationFailed",
  translationResultEyebrow: "translationResultEyebrow", translationResult: "translationResult", resultPlaceholder: "resultPlaceholder",
  copy: "copy", retranslate: "retranslate", historyEyebrow: "historyEyebrow", historyTitle: "historyTitle", noHistory: "noHistory"
};

const server = await createServer({ root: fileURLToPath(root), server: { middlewareMode: true }, appType: "custom", logLevel: "silent" });
let localeMessages;
try {
  ({ localeMessages } = await server.ssrLoadModule("/src/shared/i18n.ts"));
} finally {
  await server.close();
}

const locales = Object.keys(localeMessages);
const expectedLocales = Object.keys(browserLocaleNames);
if (locales.length !== expectedLocales.length || expectedLocales.some((locale) => !localeMessages[locale])) {
  throw new Error(`Locale catalog and browser locale mapping differ: catalog=${locales.join(",")} mapping=${expectedLocales.join(",")}`);
}

function selectFields(locale, fields) {
  const source = localeMessages[locale];
  return Object.fromEntries(Object.entries(fields).map(([outputKey, sourceKey]) => {
    const value = source[sourceKey];
    if (typeof value !== "string" || !value.trim()) throw new Error(`Locale ${locale} is missing required message ${sourceKey}.`);
    return [outputKey, value];
  }));
}

function placeholders(value) {
  return [...value.matchAll(/\{([a-z]+)\}/g)].map((match) => match[1]).sort().join(",");
}

const englishContent = selectFields("en", contentFields);
const englishBrowser = selectFields("en", browserFields);
const englishOptions = selectFields("en", optionsFields);
const contentMessages = Object.fromEntries(locales.map((locale) => {
  const messages = selectFields(locale, contentFields);
  for (const key of Object.keys(messages)) {
    if (placeholders(messages[key]) !== placeholders(englishContent[key])) throw new Error(`Locale ${locale} has invalid placeholders for ${key}.`);
    if (locale !== "en" && messages[key] === englishContent[key]) throw new Error(`Locale ${locale} has not translated ${contentFields[key]}.`);
  }
  return [locale, messages];
}));

for (const locale of locales) {
  const messages = selectFields(locale, optionsFields);
  for (const key of Object.keys(messages)) {
    if (placeholders(messages[key]) !== placeholders(englishOptions[key])) throw new Error(`Locale ${locale} has invalid placeholders for ${key}.`);
    if (locale !== "en" && messages[key] === englishOptions[key]) throw new Error(`Locale ${locale} has not translated ${optionsFields[key]}.`);
  }
}

const generatedDirectory = new URL("src/generated/", root);
await mkdir(generatedDirectory, { recursive: true });
await writeFile(new URL("content-locales.ts", generatedDirectory), `// Generated by scripts/generate-i18n.mjs. Do not edit.\nexport const contentMessages = ${JSON.stringify(contentMessages, null, 2)} as const;\n`, "utf8");

const publicLocales = new URL("public/_locales/", root);
await rm(publicLocales, { recursive: true, force: true });
await mkdir(publicLocales, { recursive: true });
for (const locale of locales) {
  const directory = new URL(`${browserLocaleNames[locale]}/`, publicLocales);
  await mkdir(directory, { recursive: true });
  const browserMessages = selectFields(locale, browserFields);
  if (locale !== "en") for (const key of Object.keys(browserMessages)) {
    if (!["extensionName", "extensionShortName"].includes(key) && browserMessages[key] === englishBrowser[key]) throw new Error(`Locale ${locale} has not translated ${browserFields[key]}.`);
  }
  const messages = Object.fromEntries(Object.entries(browserMessages).map(([key, message]) => [key, { message }]));
  await writeFile(new URL("messages.json", directory), `${JSON.stringify(messages, null, 2)}\n`, "utf8");
}

console.log(`Generated ${locales.length} content and browser locale bundles.`);
