import { translate } from "./shared/api";
import { getSettings, profileLabel, saveSettings, validateBaseUrl } from "./shared/storage";
import { setLocale, t } from "./shared/i18n";
import type { Profile, Settings, TranslationMode, UiLocalePreference } from "./shared/types";
import "./options.css";

const app = document.querySelector<HTMLDivElement>("#app")!;
let settings: Settings;
let editing: Profile | null = null;
const newProfile = (): Profile => ({ id: crypto.randomUUID(), name: "", baseUrl: "", apiKey: "", model: "", sourceLanguage: "English", targetLanguage: "Chinese", mode: "replace" });
const escape = (value: string) => value.replace(/[&<>"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]!);
const notifyProfileChange = () => chrome.runtime.sendMessage({ kind: "profilesChanged" }).catch(() => undefined);
const localizeUrlError = (error: string) => error.includes("valid absolute") ? t("invalidUrl") : error.includes("HTTPS") ? t("insecureUrl") : error.includes("credentials") ? t("credentialsUrl") : error.includes("query string") ? t("queryUrl") : error;

function render() {
  const profile = editing ?? newProfile();
  document.documentElement.lang = settings.uiLocale && settings.uiLocale !== "auto" ? settings.uiLocale : navigator.language;
  document.title = t("title");
  app.innerHTML = `<header><div class="header-row"><h1>${t("title")}</h1><label class="locale">${t("uiLanguage")}<select id="ui-locale"><option value="auto" ${!settings.uiLocale || settings.uiLocale === "auto" ? "selected" : ""}>${t("followBrowser")}</option><option value="zh-CN" ${settings.uiLocale === "zh-CN" ? "selected" : ""}>简体中文</option><option value="zh-TW" ${settings.uiLocale === "zh-TW" ? "selected" : ""}>繁體中文</option><option value="en" ${settings.uiLocale === "en" ? "selected" : ""}>English</option><option value="ja" ${settings.uiLocale === "ja" ? "selected" : ""}>日本語</option></select></label></div><p>${t("privacy")}</p></header><section class="profiles"><h2>${t("profiles")}</h2>${settings.profiles.length ? settings.profiles.map((item) => `<button class="profile ${item.id === settings.activeProfileId ? "active" : ""}" aria-pressed="${item.id === settings.activeProfileId}" data-id="${item.id}">${escape(profileLabel(item))}${item.id === settings.activeProfileId ? `<small>${t("active")}</small>` : ""}</button>`).join("") : `<p>${t("noProfiles")}</p>`}<button id="add">${t("add")}</button></section><section><h2>${editing ? t("editProfile") : t("newProfile")}</h2><form id="profile-form"><label>${t("name")}<input name="name" required value="${escape(profile.name)}" /></label><label>${t("baseUrl")}<input name="baseUrl" required placeholder="https://api.example.com/v1" value="${escape(profile.baseUrl)}" /></label><label>${t("apiKey")}<input name="apiKey" type="password" required autocomplete="off" value="${escape(profile.apiKey)}" /></label><label>${t("model")}<input name="model" required value="${escape(profile.model)}" /></label><label>${t("source")}<input name="sourceLanguage" required value="${escape(profile.sourceLanguage)}" /></label><label>${t("target")}<input name="targetLanguage" required value="${escape(profile.targetLanguage)}" /></label><label>${t("mode")}<select name="mode"><option value="replace" ${profile.mode === "replace" ? "selected" : ""}>${t("replace")}</option><option value="preserve" ${profile.mode === "preserve" ? "selected" : ""}>${t("preserve")}</option></select></label><p id="error" role="alert" aria-live="polite"></p><button>${t("save")}</button><button type="button" id="test">${t("test")}</button>${editing ? `<button type="button" id="delete">${t("remove")}</button>` : ""}</form></section>`;
  document.querySelector<HTMLSelectElement>("#ui-locale")!.onchange = async (event) => { const preference = (event.currentTarget as HTMLSelectElement).value as UiLocalePreference; settings.uiLocale = preference; setLocale(preference === "auto" ? null : preference); await saveSettings(settings); render(); };
  document.querySelectorAll<HTMLButtonElement>(".profile").forEach((button) => button.onclick = async () => { editing = settings.profiles.find((item) => item.id === button.dataset.id) ?? null; if (editing) { settings.activeProfileId = editing.id; await saveSettings(settings); await notifyProfileChange(); } render(); });
  document.querySelector("#add")!.addEventListener("click", () => { editing = null; render(); });
  document.querySelector<HTMLFormElement>("#profile-form")!.onsubmit = async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget as HTMLFormElement); const next = { id: editing?.id ?? crypto.randomUUID(), name: String(data.get("name")).trim(), baseUrl: String(data.get("baseUrl")).trim(), apiKey: String(data.get("apiKey")).trim(), model: String(data.get("model")).trim(), sourceLanguage: String(data.get("sourceLanguage")).trim(), targetLanguage: String(data.get("targetLanguage")).trim(), mode: data.get("mode") as TranslationMode }; const error = validateBaseUrl(next.baseUrl); if (error) return showError(localizeUrlError(error)); settings.profiles = [...settings.profiles.filter((item) => item.id !== next.id), next]; settings.activeProfileId = next.id; await saveSettings(settings); await notifyProfileChange(); editing = next; render(); };
  document.querySelector("#delete")?.addEventListener("click", async () => { if (!editing) return; settings.profiles = settings.profiles.filter((item) => item.id !== editing!.id); if (settings.activeProfileId === editing.id) settings.activeProfileId = settings.profiles[0]?.id ?? null; await saveSettings(settings); await notifyProfileChange(); editing = null; render(); });
  document.querySelector("#test")!.addEventListener("click", async () => { const form = document.querySelector<HTMLFormElement>("#profile-form")!; const data = new FormData(form); const draft = { ...profile, ...Object.fromEntries(data) } as Profile; const error = validateBaseUrl(draft.baseUrl); if (error) return showError(localizeUrlError(error)); try { await translate(draft, "Hello"); settings.profiles = [...settings.profiles.filter((item) => item.id !== draft.id), draft]; settings.activeProfileId = draft.id; await saveSettings(settings); await notifyProfileChange(); editing = draft; render(); showError(t("connected"), false); } catch (caught) { showError(caught instanceof Error ? caught.message : t("connectionFailed")); } });
}
function showError(message: string, failure = true) { const element = document.querySelector<HTMLParagraphElement>("#error")!; element.textContent = message; element.className = failure ? "error" : "success"; }
getSettings().then((loaded) => { settings = loaded; setLocale(loaded.uiLocale && loaded.uiLocale !== "auto" ? loaded.uiLocale : null); render(); });
