import { translate } from "./shared/api";
import { getSettings, profileLabel, saveSettings, validateBaseUrl } from "./shared/storage";
import { t } from "./shared/i18n";
import type { Profile, Settings, TranslationMode } from "./shared/types";
import "./options.css";

const app = document.querySelector<HTMLDivElement>("#app")!;
let settings: Settings;
let editing: Profile | null = null;
const newProfile = (): Profile => ({ id: crypto.randomUUID(), name: "", baseUrl: "", apiKey: "", model: "", sourceLanguage: "English", targetLanguage: "Chinese", mode: "replace" });
const escape = (value: string) => value.replace(/[&<>"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]!);

function render() {
  const profile = editing ?? newProfile();
  app.innerHTML = `<header><h1>${t("title")}</h1><p>${t("privacy")}</p></header><section class="profiles"><h2>${t("profiles")}</h2>${settings.profiles.length ? settings.profiles.map((item) => `<button class="profile ${item.id === settings.activeProfileId ? "active" : ""}" data-id="${item.id}">${escape(profileLabel(item))}</button>`).join("") : `<p>${t("noProfiles")}</p>`}<button id="add">${t("add")}</button></section><section><h2>${editing ? t("editProfile") : t("newProfile")}</h2><form id="profile-form"><label>${t("name")}<input name="name" required value="${escape(profile.name)}" /></label><label>${t("baseUrl")}<input name="baseUrl" required placeholder="https://api.example.com/v1" value="${escape(profile.baseUrl)}" /></label><label>${t("apiKey")}<input name="apiKey" type="password" required value="${escape(profile.apiKey)}" /></label><label>${t("model")}<input name="model" required value="${escape(profile.model)}" /></label><label>${t("source")}<input name="sourceLanguage" required value="${escape(profile.sourceLanguage)}" /></label><label>${t("target")}<input name="targetLanguage" required value="${escape(profile.targetLanguage)}" /></label><label>${t("mode")}<select name="mode"><option value="replace" ${profile.mode === "replace" ? "selected" : ""}>${t("replace")}</option><option value="preserve" ${profile.mode === "preserve" ? "selected" : ""}>${t("preserve")}</option></select></label><p id="error" role="alert"></p><button>${t("save")}</button><button type="button" id="test">${t("test")}</button>${editing ? `<button type="button" id="delete">${t("remove")}</button>` : ""}</form></section>`;
  document.querySelectorAll<HTMLButtonElement>(".profile").forEach((button) => button.onclick = () => { editing = settings.profiles.find((item) => item.id === button.dataset.id) ?? null; render(); });
  document.querySelector("#add")!.addEventListener("click", () => { editing = null; render(); });
  document.querySelector<HTMLFormElement>("#profile-form")!.onsubmit = async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget as HTMLFormElement); const next = { id: editing?.id ?? crypto.randomUUID(), name: String(data.get("name")).trim(), baseUrl: String(data.get("baseUrl")).trim(), apiKey: String(data.get("apiKey")).trim(), model: String(data.get("model")).trim(), sourceLanguage: String(data.get("sourceLanguage")).trim(), targetLanguage: String(data.get("targetLanguage")).trim(), mode: data.get("mode") as TranslationMode }; const error = validateBaseUrl(next.baseUrl); if (error) return showError(error); settings.profiles = [...settings.profiles.filter((item) => item.id !== next.id), next]; settings.activeProfileId = next.id; await saveSettings(settings); editing = next; render(); };
  document.querySelector("#delete")?.addEventListener("click", async () => { if (!editing) return; settings.profiles = settings.profiles.filter((item) => item.id !== editing!.id); if (settings.activeProfileId === editing.id) settings.activeProfileId = settings.profiles[0]?.id ?? null; await saveSettings(settings); editing = null; render(); });
  document.querySelector("#test")!.addEventListener("click", async () => { const form = document.querySelector<HTMLFormElement>("#profile-form")!; const data = new FormData(form); const draft = { ...profile, ...Object.fromEntries(data) } as Profile; const error = validateBaseUrl(draft.baseUrl); if (error) return showError(error); try { await translate(draft, "Hello"); settings.profiles = [...settings.profiles.filter((item) => item.id !== draft.id), draft]; settings.activeProfileId = draft.id; await saveSettings(settings); editing = draft; render(); showError("Connection succeeded. This profile is now active.", false); } catch (caught) { showError(caught instanceof Error ? caught.message : "Connection failed."); } });
}
function showError(message: string, failure = true) { const element = document.querySelector<HTMLParagraphElement>("#error")!; element.textContent = message; element.className = failure ? "error" : "success"; }
getSettings().then((loaded) => { settings = loaded; render(); });
